#PROYECTO FINAL
import os#IMPORTAR
os.system("cls")#LIMPIAR PANTALLA
print("\a\n\t\t\t\t*PROYECTO FINAL*\n\n")#SE MOSTARA EN PANTALLA TODO LO QUE ESTE EN EL PARENTESIS 
print("PRUEBA COVID-19\nPOR FAVOR INGRESE HASTA 10 USUARIOS\n ")#SE MOSTRARA POR PANTALLA TODO LO QUE ESTE EN EL PARENTESIS. LECTURA DE DATOS POR TECLADO
print("0 PERSONAS CON COVID: SEMAFORO VERDE\n1-3 PERSONAS CON COVID: SEMAFORO AMARILLO\n4-6 PERSONAS CON COVID: SEMAFORO NARANJA\n7-10 PERSONAS CON COVID: SEMAFORO ROJO ")
#SE MOSTARA EN PANTALLA TODO LO QUE ESTE EN EL PARENTESIS 
print("INDICADOR [0-0.7] NEGATIVO\nINDICADOR [0.8-1] POSITIVO\n")#SE MOSTARA EN PANTALLA TODO LO QUE ESTE EN EL PARENTESIS 
op='0'#INICIALIZAMOS EN 0 LA VARIABLE
datos=[]#EN ESTA LISTA SE ALMACENAREMOS LAS EDADES Y LOS INDICADORES
edades=[]#EN ESTA LISTA ALMACENAREMOS LAS EDADES
indicadores=[]#EN ESTA LISTA ALMACENAREMOS LOS INDICADORES 
while(op!='2'):#MIENTRAS OPCCION SEA DIFERENTE DE 2 SE EJECUTARAN LAS SIGUIENTES ACCIONES
	print(" 1) LLENAR\n 2) SALIR\n")#SE MOSTARA EN PANTALLA TODO LO QUE ESTE EN EL PARENTESIS 
	op=input("ELIGE UNA OPCION : ")#SE MOSTRARA POR PANTALLA TODO LO QUE ESTE EN EL PARENTESIS. LECTURA DE DATOS POR TECLADO
	print("\n")#SALTO DE LINEA
	if op=='1':#SI op ES IGUAL A '1', SE EJECUTARA EL CONTENIDO 
		edad=input("EDAD : ")#LECTURA DE DATOS. DAR EL VALOR DE EDAD
		indicador=input("INDICADOR [0-1]: ")#LECTURA DE DATOS. DAR EL VALOR DEL INDICADOR
		print("\n\n")#DOS SALTOS DE LINEA
		if indicador>='0.8':#SI EL VALOR DE INDICADOR ES MAYOR O IGUAL A 8 SE EJECUTARA EL CONTENIDO 
			print("USTED TIENE COVID\n ")#SE MOSTRARA EN PANTALLA TODO LO QUE ESTE EN EL PARENTESIS
		elif indicador<'0.8':#SI EL VALOR DE INDICADOR ES MENOR A 8 SE EJECUTARA EL CONTENIDO 
			print("USTED NO TIENE COVID\n ")#SE MOSTRARA EN PANTALLA TODO LO QUE ESTE EN EL PARENTESIS
		Y=indicador#GUARDAMOS EN Y LOS DATOS DE INDICADOR
		X=edad#GUARDAMOS EN X LOS DATOS DE EDAD
		reg="EDAD "+edad+' : '+" INDICADOR "+indicador+'\n'#GUARDAMOS EN REG LOS VALORES DE EDAD E INDICADOR 
		datos.append(reg)#ALMACENAMOS LOS DATOS DE REG EN LA LISTA datos=[]
		edades.append(X)#ALMACENAMOS LOS DATOS DE X EN LA LISTA edades=[]
		indicadores.append(Y)#ALMACENAMOS LOS DATOS DE Y EN LA LISTA indicadores=[]
	elif op=='2':#EL PROGRAMA SE SEGUIRA EJECUTANDO HASTA QUE EL USUARIO ESCOJA LA OPCION 2, EN ESE MOMENTO TERMINARA EL PROGRAMA 
		print("GRACIAS, VUELVA PRONTO\n")#SE MOSTARA EN PANTALLA TODO LO QUE ESTE EN EL PARENTESIS 
	else:#SI EL USUARIO NO ELIGE LA OPCION 1 NI LA OPCCION 2, APARECERA EL SIGUIENTE MENSAJE 
		print("OPC NO VALIDA\n")#SE MOSTARA EN PANTALLA TODO LO QUE ESTE EN EL PARENTESIS 

print("\n")#SALTO DE LINEA 
print("DATOS: ")#SE MOSTARA EN PANTALLA TODO LO QUE ESTE EN EL PARENTESIS
print(datos)#IMPRIMIRA LOS DATOS GUARDADOS EN datos=[]
print("\n")#SALTO DE LINEA 
print("EDADES: ")#SE MOSTARA EN PANTALLA TODO LO QUE ESTE EN EL PARENTESIS
print(edades)#IMPRIMIRA LOS DATOS GUARDADOS EN edades=[]
print("\n")#SALTO DE LINEA 
print("INDICADORES: ")#SE MOSTARA EN PANTALLA TODO LO QUE ESTE EN EL PARENTESIS
print(indicadores)#IMPRIMIRA LOS DATOS GUARDADOS EN indicadores=[]
print("\n")#SALTO DE LINEA 

for x in range(len(indicadores)-1,-1,-1):#CICLO PARA ELIMINAR DATOS DE LAS LISTAS 
	if indicadores[x]=='0':#SI X ES IGUAL A '0' REALIZARA LA ACCION SIGUIENTE
		indicadores.pop(x)#ELIMINAR TODOS LOS '0' DE LA LISTA
for x in range(len(indicadores)-1,-1,-1):#CICLO PARA ELIMINAR DATOS DE LAS LISTAS
	if indicadores[x]=='0.1':#SI X ES IGUAL A '0.1' REALIZARA LA ACCION SIGUIENTE
		indicadores.pop(x)#ELIMINAR TODOS LOS '0.1' DE LA LISTA
for x in range(len(indicadores)-1,-1,-1):#CICLO PARA ELIMINAR DATOS DE LAS LISTAS
	if indicadores[x]=='0.2':#SI X ES IGUAL A '0.2' REALIZARA LA ACCION SIGUIENTE
		indicadores.pop(x)#ELIMINAR TODOS LOS '0.2' DE LA LISTA
for x in range(len(indicadores)-1,-1,-1):#CICLO PARA ELIMINAR DATOS DE LAS LISTAS
	if indicadores[x]=='0.3':#SI X ES IGUAL A '0.3' REALIZARA LA ACCION SIGUIENTE
		indicadores.pop(x)#ELIMINAR TODOS LOS '0.3' DE LA LISTA
for x in range(len(indicadores)-1,-1,-1):#CICLO PARA ELIMINAR DATOS DE LAS LISTAS
	if indicadores[x]=='0.4':#SI X ES IGUAL A '0.4' REALIZARA LA ACCION SIGUIENTE
		indicadores.pop(x)#ELIMINAR TODOS LOS '0.4' DE LA LISTA
for x in range(len(indicadores)-1,-1,-1):#CICLO PARA ELIMINAR DATOS DE LAS LISTAS
	if indicadores[x]=='0.5':#SI X ES IGUAL A '0.5' REALIZARA LA ACCION SIGUIENTE
		indicadores.pop(x)#ELIMINAR TODOS LOS '0.5' DE LA LISTA
for x in range(len(indicadores)-1,-1,-1):#CICLO PARA ELIMINAR DATOS DE LAS LISTAS
	if indicadores[x]=='0.6':#SI X ES IGUAL A '0.6' REALIZARA LA ACCION SIGUIENTE
		indicadores.pop(x)#ELIMINAR TODOS LOS '0.6' DE LA LISTA
for x in range(len(indicadores)-1,-1,-1):#CICLO PARA ELIMINAR DATOS DE LAS LISTAS
	if indicadores[x]=='0.7':#SI X ES IGUAL A '0.7' REALIZARA LA ACCION SIGUIENTE
		indicadores.pop(x)#ELIMINAR TODOS LOS '0.7' DE LA LISTA
print("DE LOS USUARIOS INGRESADOS, EL NUMERO QUE TIENE COVID ES :"+str(len(indicadores)))#CONVERTIMOS A CARACTER LA LONGITUD DE LA CADENA RESTANTE
print("\n")#SALTO DE LINEA

if len(indicadores)==0:#SI LA LONGITUD DE LA CADENA ES IGUAL A 0 SE EJECUTARA LO SIGUIENTE
	print("ESTAMOS EN SEMAFORO VERDE!")#SE MOSTARA EN PANTALLA TODO LO QUE ESTE EN EL PARENTESIS
elif len(indicadores)>=1 and len(indicadores)<=3:#SI LA LONGITUD DE LA CADENA ES MAYOR O IGUAL A 1 Y SI LA LONGITUD DE LA CEDENA ES MENOR O IGUAL A 30 SE EJECUTARA LO SIGUIENTE
	print("ESTAMOS EN SEMAFORO AMARILLO")#SE MOSTARA EN PANTALLA TODO LO QUE ESTE EN EL PARENTESIS
elif len(indicadores)>=4 and len(indicadores)<=6:#SI LA LONGITUD DE LA CADENA ES MAYOR O IGUAL A 31 Y SI LA LONGITUD DE LA CEDENA ES MENOR O IGUAL A 70 SE EJECUTARA LO SIGUIENTE
	print("ESTAMOS EN SEMAFORO NARANJA")#SE MOSTARA EN PANTALLA TODO LO QUE ESTE EN EL PARENTESIS
elif len(indicadores)>=7 and len(indicadores)<=10:#SI LA LONGITUD DE LA CADENA ES MAYOR O IGUAL A 71 Y SI LA LONGITUD DE LA CEDENA ES MENOR O IGUAL A 100 SE EJECUTARA LO SIGUIENTE
	print("X ESTAMOS EN SEMAFORO ROJO X")#SE MOSTARA EN PANTALLA TODO LO QUE ESTE EN EL PARENTESIS

print("\n")#SALTO DE LINEA

a=(edades)#GUARDAREMOS EN a LOS VALORES DE edades=[]
suma=0#INICIALIZAREMOS EN O LA VARIABLE suma
y=0#INICIALIZAREMOS EN 0 LA VARIABLE y
for elemento in a:#CICLO PARA REALIZAR EL PROMEDIO 
	suma+=int(elemento)#CONVERTIMOS A ENTERO LA VARIABLE elemento
	y+=1#SE AUMENTARA LA VARIABLE y CADA QUE SE REINICIE EL CICLO 
PROMEDIO=suma/y#GUARDAMOS EN PROMEDIO EL RESULTADO DE LA OPERACION 
print ("EL PROMEDIO DE EDADES TOTALES ES : "+str(PROMEDIO))#CONVERTIMOS A CARACTER LA VARIABLE PROMEDIO 
print("\n")#SALTO DE LINEA

opc='0'#INICIALIZAMOS EN 0 LA VARIABLE
opc2='0'#INICIALIZAMOS EN 0 LA VARIABLE
x='0'#INICIALIZAMOS EN 0 LA VARIABLE
print("USTED FUE UN USUARIO CON COVID? ")#SE MOSTARA EN PANTALLA TODO LO QUE ESTE EN EL PARENTESIS
print(" 1) SI\n 2) NO\n")#SE MOSTARA EN PANTALLA TODO LO QUE ESTE EN EL PARENTESIS 
opc=input("ELIGE UNA OPCION : ")#SE MOSTRARA POR PANTALLA TODO LO QUE ESTE EN EL PARENTESIS. LECTURA DE DATOS POR TECLADO
print("\n")#SALTO DE LINEA
if opc=='1':#SI op ES IGUAL A '1', SE EJECUTARA EL CONTENIDO 
	print("CUAL FUE TU INDICADOR?\n")#SE MOSTARA EN PANTALLA TODO LO QUE ESTE EN EL PARENTESIS
	print(" 1) [0.8] 2) [0.8-1]\n")#SE MOSTARA EN PANTALLA TODO LO QUE ESTE EN EL PARENTESIS
	opc2=input("ELIGE UNA OPCCION : \n")#SE MOSTRARA POR PANTALLA TODO LO QUE ESTE EN EL PARENTESIS. LECTURA DE DATOS POR TECLADO
	if opc2=='1':#SI opc2 ES IGUAL A '1', SE EJECUTARA EL CONTENIDO
		print("USTED ESTA DELICADO DE SALUD\n")#SE MOSTARA EN PANTALLA TODO LO QUE ESTE EN EL PARENTESIS
		print("CONSULTE NUESTRA BASE DE DATOS (Productos)\n")#SE MOSTARA EN PANTALLA TODO LO QUE ESTE EN EL PARENTESIS
		print("CONSULTE CON SU MEDICO QUE PRODUCTO CONSUMIR\n")#SE MOSTARA EN PANTALLA TODO LO QUE ESTE EN EL PARENTESIS
		def pag(cantidad,precio):#DEFINIR FUNCION QUE DEPENDE DE LA CANTIDAD Y EL PRECIO 
			A=cantidad*precio#GUARDAR EL RESULTADO DE LA CANTIDAD DE PRODUCTOS POR EL PRECIO EN 'A'
			return(A)#REGRESA EL VALOR DE 'A' QUE SERA EL PRECIO TOTAL
		import pandas as pd#IMPORTAR PANDAS
		x=pd.read_csv('Productos.csv')#LEER DATOS, NOMBRE DE NUESTRO ARCHIVO
		df=pd.DataFrame(x)#ESTRUCTURA DE DATOS DE PANDAS
		producto=input('ES NECESARIO QUE ADQUIERAS ALGUN PRODUCTO DE NUESTRA COLUMA (SEGUNDO CASO)\nPOR FAVOR ESCRIBELO A CONTINUACION TAL CUAL APARECE: \n')
		#LECTURA DE DATOS. PRODUCTO
		cantidad=int(input('CUANTAS PIEZAS LLEVARAS?\n'))#LECTURA DE DATOS. NUMERO DE PIEZAS 
		precio=df[df['SEGUNDO CASO']==producto]['COSTO']#BUSCA EN LA COLUMA 'SEGUNDO CASO' EL PRODUCTO INTRODUCIDO Y RECUPERA LA COLUMNA COSTO
		print("\n")#SALTO DE LINEA
		print ("EL PRECIO TOTAL ES DE: ")#SE MOSTARA EN PANTALLA TODO LO QUE ESTE EN EL PARENTESIS
		print(pag(cantidad,precio))#IMPRIMIR EL RESULTADO DE LA FUNCION pag
		print("\n")#SALTO DE LINEA
		print("GRACIAS POR SU COMPRA!!")#SE MOSTARA EN PANTALLA TODO LO QUE ESTE EN EL PARENTESIS
		
	elif opc2=='2':#SI opc2 ES IGUAL A 2, SE EJECUTARA LO SIGUIENTE
		print("USTED ESTA MUY GRAVE DE SALUD\n")#SE MOSTARA EN PANTALLA TODO LO QUE ESTE EN EL PARENTESIS
		print("CONSULTE NUESTRA BASE DE DATOS (Productos)\n")#SE MOSTARA EN PANTALLA TODO LO QUE ESTE EN EL PARENTESIS
		def pag(cantidad,precio):#DEFINIR FUNCION QUE DEPENDE DE LA CANTIDAD Y EL PRECIO 
			A=cantidad*precio#GUARDAR EL RESULTADO DE LA CANTIDAD DE PRODUCTOS POR EL PRECIO EN 'A'
			return(A)#REGRESA EL VALOR DE 'A' QUE SERA EL PRECIO TOTAL
		import pandas as pd#IMPORTAR PANDAS
		x=pd.read_csv('Productos.csv')#LEER DATOS, NOMBRE DE NUESTRO ARCHIVO
		df=pd.DataFrame(x)#ESTRUCTURA DE DATOS DE PANDAS
		producto=input('NECESITA ADQUIRIR EL PRODUCTO DE NUESTRA COLUMA (TERCER CASO)\nPOR FAVOR ESCRIBELO A CONTINUACION TAL CUAL APARECE: \n')#LECTURA DE DATOS. PRODUCTO
		cantidad=int(input('CUANTOS EQUIPOS LLEVARAS?\n'))#LECTURA DE DATOS. NUMERO DE EQUIPOS
		precio=df[df['TERCER CASO']==producto]['MONTO']#BUSCA EN LA COLUMA 'TERCER CASO' EL PRODUCTO INTRODUCIDO Y RECUPERA LA COLUMNA MONTO
		print("\n")#SALTO DE LINEA
		print ("EL PRECIO TOTAL ES DE: ")#SE MOSTARA EN PANTALLA TODO LO QUE ESTE EN EL PARENTESIS
		print(pag(cantidad,precio))#IMPRIMIR EL RESULTADO DE LA FUNCION pag
		print("GRACIAS POR SU COMPRA!!")#SE MOSTARA EN PANTALLA TODO LO QUE ESTE EN EL PARENTESIS
		print("\n")#SALTO DE LINEA
		print("\nAUN SE SIETE MUY GRAVDE DE SALUD?\n ")#SE MOSTARA EN PANTALLA TODO LO QUE ESTE EN EL PARENTESIS
		print(" 10) SI\n 20) NO\n")#SE MOSTARA EN PANTALLA TODO LO QUE ESTE EN EL PARENTESIS
		x=input("ELIGE UNA OPCION : \n")#SE MOSTRARA POR PANTALLA TODO LO QUE ESTE EN EL PARENTESIS. LECTURA DE DATOS POR TECLADO
		if x=='10':#SI x='10' SE EJECUTARA LO SIGUIENTE
			print("ES NECESARIO ACUDIR A SU HOSPITAL MAS CERCANO\n")#SE MOSTARA EN PANTALLA TODO LO QUE ESTE EN EL PARENTESIS
			print("EL HOSPITAL ESTA LLENO\nPACIENTES: \n")#SE MOSTARA EN PANTALLA TODO LO QUE ESTE EN EL PARENTESIS
			cola=["DANIEL","JUAN","FERNANDO","DANIELA"]#DEFINIMOS LOS ELEMENTOS DE LA COLA
			print(cola)#IMPRIME LOS ELEMENTOS DE LA COLA
			print("\nINGRESA TU NOMBRE PARA HACER UNA CITA:\n ")#SE MOSTARA EN PANTALLA TODO LO QUE ESTE EN EL PARENTESIS
			nombre=input("CUAL ES TU NOMBRE? ")#LECTURA DE DATOS. INGRESAR TU NOMBRE 
			cola.pop(0)#ELIMINAR ESE ELEMENTO
			cola.append(nombre)#AGREGAR A LOS ELEMENTOS DE LA COLA 'nombre'
			print("\nSE HA DESOCUPADO UN LUGAR!\n")#SE MOSTARA EN PANTALLA TODO LO QUE ESTE EN EL PARENTESIS
			print(cola)#IMPRIMIR LOS NUEVOS ELEMENTOS DE LA COLA
			print("ESPERE SU TURNO PARA SER ATENDIDO \n")#SE MOSTARA EN PANTALLA TODO LO QUE ESTE EN EL PARENTESIS
		elif x=='20':#SI x='20' SE EJECUTARA LO SIGUIENTE
			print("RECUPERECE PRONTO")#SE MOSTARA EN PANTALLA TODO LO QUE ESTE EN EL PARENTESIS
		else:#SI EL USUARIO NO ELIGE LA OPCION 1 NI LA OPCCION 2, APARECERA EL SIGUIENTE MENSAJE 
			print("OPCION NO VALIDA\n")#SE MOSTARA EN PANTALLA TODO LO QUE ESTE EN EL PARENTESIS
	else:#SI EL USUARIO NO ELIGE LA OPCION 10 NI LA OPCCION 20, APARECERA EL SIGUIENTE MENSAJE 
		print("OPCION NO VALIDA\n")#SE MOSTARA EN PANTALLA TODO LO QUE ESTE EN EL PARENTESIS
	
elif opc=='2':#SI opc ES IGUAL A 2, SE EJECUTARA LO SIGUIENTE
	print("USTED ESTA BIEN DE SALUD\n")#SE MOSTARA EN PANTALLA TODO LO QUE ESTE EN EL PARENTESIS
	print("CONSULTE NUESTRA BASE DE DATOS (Productos)\n")#SE MOSTARA EN PANTALLA TODO LO QUE ESTE EN EL PARENTESIS
	def pago(cantidad,precio):#DEFINIR A LA FUNCION
		A=cantidad*precio#GUARDAR EL RESULTADO DE LA CANTIDAD DE PRODUCTOS POR EL PRECIO EN 'A'
		return(A)#REGRESA EL VALOR DE 'A' QUE SERA EL PRECIO TOTAL
			
	import pandas as pd#IMPORTAR PANDAS
	x=pd.read_csv('Productos.csv')#LEER DATOS, NOMBRE DE NUESTRO ARCHIVO
	df=pd.DataFrame(x)#ESTRUCTURA DE DATOS DE PANDAS
		
	producto=input('TE RECOMENDAMOS ADQUIRIR ALGUNO DE LOS PRODUCTOS DE NUESTRA COLUMA (PRIMER CASO)PARA UNA MAYOR SEGURIDAD\nPOR FAVOR ESCRIBELO A CONTINUACION TAL CUAL APARECE: ')
	#LECTURA DE DATOS. PRODUCTO
	cantidad=int(input('CUANTAS PIEZAS LLEVARAS?: '))#LECTURA DE DATOS. NUMERO DE PIEZAS 
	precio=df[df['PRIMER CASO']==producto]['PRECIO']#BUSCA EN LA COLUMA 'PRIMER CASO' EL PRODUCTO INTRODUCIDO Y RECUPERA LA COLUMNA PRECIO
	print("\n")#SALTO DE LINEA
	print ("EL PRECIO TOTAL ES DE: ") #SE MOSTARA EN PANTALLA TODO LO QUE ESTE EN EL PARENTESIS
	print(pago(cantidad,precio))#IMPRIMIR EL RESULTADO DE LA FUNCION pago
	print("GRACIAS POR SU COMPRA!!")#SE MOSTARA EN PANTALLA TODO LO QUE ESTE EN EL PARENTESIS
	print("\n")#SALTO DE LINEA
else:#SI EL USUARIO NO ELIGE LA OPCION 1 NI LA OPCCION 2, APARECERA EL SIGUIENTE MENSAJE 
	print("OPC NO VALIDA\n")#SE MOSTARA EN PANTALLA TODO LO QUE ESTE EN EL PARENTESIS 


